Added modal, done with groups-ui logic
summer-troopers/better-moodle-ui pull request #29
Opened 2018-08-03 13:03 UTC by ionharea

2018-08-03 13:48 UTC, vadim11041996 requested changes

2018-08-03 13:48 UTC, vadim11041996 commented on src/app/core/services/api/backend-api.service.ts
> +    console.log(path);
delete console.log

2018-08-03 13:48 UTC, vadim11041996 commented on src/app/modules/groups/components/add-group-modal/add-group-modal.component.html
> +<button type="button" class="btn btn-primary" (click)="openModal(template)">Add a new group</button>
modal button don't need to be with modal in the same file

2018-08-03 13:48 UTC, vadim11041996 commented on src/app/modules/groups/components/add-group-modal/add-group-modal.component.ts
> +import { SpecialtiesService } from '../../../specialties/specialties.service';
let a new empty line between angular imports and your imports

2018-08-03 13:48 UTC, vadim11041996 commented on src/app/modules/groups/components/edit-group-modal/edit-group-modal.component.html
> +<ng-template #template>
same problem with button, not in the right file

2018-08-03 13:48 UTC, vadim11041996 commented on src/app/modules/groups/components/edit-group-modal/edit-group-modal.component.ts
> +import { GroupDetailsPageComponent } from '@modules/groups/containers';
new empty line between angular imports and your imports

2018-08-03 13:48 UTC, vadim11041996 commented on src/app/modules/groups/components/edit-group-modal/edit-group-modal.component.ts
> +      this.id = params.id;
if you get id from param, that mean you already should store it somewhere, and here just reuse it.

2018-08-03 13:48 UTC, vadim11041996 commented on src/app/modules/groups/containers/group-details-page/group-details-page.component.ts
> +  }
If you want consistent  reactive programming style and want to be within your application to always use observables even for single events, then use observables , how you did , If that doesn't matter to you, use  toPromise(), but, with .map() , it's better to use subscribe

2018-08-03 13:48 UTC, vadim11041996 commented on src/app/modules/groups/containers/groups-page/groups-page.component.ts
> +import { Subscription } from 'rxjs';
the same way with one empty line

2018-08-03 13:48 UTC, vadim11041996 commented on src/app/modules/groups/groups.module.ts
> +import { EditGroupModalComponent } from './components/edit-group-modal/edit-group-modal.component';
import {groupsRoutes}  
import { AddGroupModalComponent } 
difference?

2018-08-03 13:48 UTC, vadim11041996 commented on src/app/modules/groups/groups.service.ts
> +import { map } from 'rxjs/operators';
sort imports

2018-08-03 13:48 UTC, vadim11041996 commented on src/app/modules/specialties/containers/specialty-details-page/specialty-details-page.component.ts
> +    this.specialtyService.updateSpecialty(this.id, this.specialty).toPromise();
same way with toPromise()

2018-08-03 13:48 UTC, vadim11041996 commented on src/environments/environment.ts
> +  apiUrl: 'http://localhost:8080/api/v1'
everybody has different port, but on master let in be as it was from start

2018-08-03 14:11 UTC, mrRobot157 commented on src/app/modules/groups/components/edit-group-modal/edit-group-modal.component.ts
> +      this.id = params.id;
I use it in another way , cause i dont wanna send it in the new group to the db to be sure there is no way i get an error ;)

2018-08-03 14:13 UTC, mrRobot157 commented on src/app/modules/groups/containers/group-details-page/group-details-page.component.ts
> +  }
please repeat :D

2018-08-03 14:37 UTC, alexandrubereghici commented on src/environments/environment.ts
> +  apiUrl: 'http://localhost:8080/api/v1'
create different profiles for environment

2018-08-06 14:48 UTC, crischiucucu requested changes

2018-08-06 14:48 UTC, crischiucucu commented on src/app/modules/groups/containers/groups-page/groups-page.component.ts
> +    this.subscription = this.groupsService.getGroups().subscribe((groups: Array<Group>) => this.groups = groups);
Same issue with subscriptions to an observable from http-client requests...

2018-08-06 14:48 UTC, crischiucucu commented on src/app/modules/groups/groups.module.ts
>  import {groupsRoutes} from '@modules/groups/groups.routes';
Please group the imports as I explained earlier :)

2018-08-06 14:48 UTC, crischiucucu commented on src/app/modules/groups/groups.service.ts
> +import { Injectable } from '@angular/core';
Same issue with grouping imports :)

2018-08-06 14:48 UTC, crischiucucu commented on src/app/modules/groups/groups.service.ts
> +      .pipe(map(result => result));
Why do you need pipe and map if you don't modify the returned observable?

2018-08-06 14:48 UTC, crischiucucu commented on src/app/modules/specialties/components/edit-specialty-modal/edit-specialty-modal.component.ts
> +import { Component, OnInit } from '@angular/core';
Please revise the add and edit modals components. For reusing code you should have a common component used in both cases :)

2018-08-06 14:48 UTC, crischiucucu commented on src/app/modules/specialties/containers/specialty-details-page/specialty-details-page.component.html
> +<div class="container">
You could use a div and add to it a class="container space-30" instead of adding a new div just for giving it a class. Usually it's recommended to minimize the structural elements if it's possible.

2018-08-06 14:48 UTC, crischiucucu commented on src/app/modules/specialties/containers/specialty-details-page/specialty-details-page.component.html
> +      <input type="text"  class="input-group-text" *ngIf="group" [(ngModel)]="group.idSpecialty"
Could you rename the property group.idSpecialty to group.specialtyId it's much readable.

2018-08-06 14:48 UTC, crischiucucu commented on src/app/modules/specialties/containers/specialty-details-page/specialty-details-page.component.html
> +             [attr.readOnly]="isEditable ? null : ''" [ngModelOptions]="{standalone: true}" required >
Please revise other comments related to the same issue.

2018-08-06 14:48 UTC, crischiucucu commented on src/app/modules/specialties/containers/specialty-details-page/specialty-details-page.component.html
> +    <form  method="post">
I think the method attribute is not necessary as you don't use the javascript native submit

2018-08-06 14:48 UTC, crischiucucu commented on src/app/modules/specialties/containers/specialty-details-page/specialty-details-page.component.ts
> +      this.subscriptions.push(this.specialtyService.getSpecialty(this.id).subscribe((element) => {
It's recommended to give a more appropriate name here. Element can be replaced with a more contextual name like: specialty

2018-08-06 14:48 UTC, crischiucucu commented on src/app/modules/specialties/specialties.service.ts
> +        console.log(result);
You should delete console.log :)

2018-08-06 14:48 UTC, crischiucucu commented on src/app/modules/specialties/specialties.service.ts
> +      .pipe(map(result => result));
You could do: return this.api.get(`.....`); if you don't apply any modification onto the result...

2018-08-06 14:48 UTC, crischiucucu commented on src/app/modules/specialties/specialties.service.ts
> +      .pipe(map(result => result));
same here

2018-08-06 14:48 UTC, crischiucucu commented on src/app/shared/models/group.ts
> +  idSpecialty: string;
please rename idSpeciality in specialtyId

2018-08-06 14:48 UTC, crischiucucu commented on src/tslint.json
> +      "max-line-length": false
Usually the tslint rules must not be disabled, so please leave like it was :)

2018-08-06 14:56 UTC, mrRobot157 commented on src/app/modules/groups/components/add-group-modal/add-group-modal.component.html
> +          <option *ngFor="let specialty of specialties" value="{{specialty.name}}">{{specialty.id}}</option>
I do set specialty id in db , but in datalist display all the specialities for users so they can check one from list

2018-08-06 18:00 UTC, vadim11041996 requested changes

2018-08-07 06:46 UTC, mrRobot157 commented on src/app/modules/groups/groups.module.ts
> +import { EditGroupModalComponent } from './components/edit-group-modal/edit-group-modal.component';
what do you mean ?

2018-08-07 13:45 UTC, mrRobot157 commented on src/app/modules/groups/components/add-group-modal/add-group-modal.component.ts
> +    this.subscriptions.push(this.groupsService.addGroup(newGroup).subscribe(() => {
In more detail please , what dont you like ?

2018-08-07 13:46 UTC, mrRobot157 commented on src/app/modules/groups/components/add-group-modal/add-group-modal.component.html
> +
here too , explain why should i remove this

2018-08-07 13:48 UTC, mrRobot157 commented on src/app/modules/groups/containers/groups-page/groups-page.component.ts
> +  }
subscribe anyway is used on takeUntil , perhaps you were meaning unsubscribe ?

2018-08-07 13:48 UTC, mrRobot157 commented on src/app/modules/specialties/components/add-specialty-modal/add-specialty-modal.component.html
> +
What is here wrong with styling ?

2018-08-07 13:49 UTC, mrRobot157 commented on src/app/modules/specialties/components/add-specialty-modal/add-specialty-modal.component.ts
> +  openModal(template: TemplateRef<any>) {
Explain please in more details , like properly , what is wrong , and why i should do this way and not let it as it was

2018-08-07 13:52 UTC, mrRobot157 commented on src/app/modules/specialties/containers/specialty-details-page/specialty-details-page.component.ts
> +    this.specialtiesService.deleteSpecialty(this.id).toPromise();
what is  it ?

2018-08-07 13:53 UTC, mrRobot157 commented on src/app/modules/groups/components/add-group-modal/add-group-modal.component.html
> +<button type="button" class="btn btn-primary" (click)="openModal(template)">Add a new group</button>
is it a problem ?

2018-08-07 13:54 UTC, mrRobot157 commented on src/app/modules/groups/components/edit-group-modal/edit-group-modal.component.html
> +<ng-template #template>
what do u mean by "not in the right file ?" it goes !

2018-08-07 14:10 UTC, mrRobot157 commented on src/app/modules/groups/components/add-group-modal/add-group-modal.component.html
> +    <form [formGroup]="groupForm" (submit)="onSubmit()">
none of us till now have use ng-submit , and we now need all change submit to ng-submit ?

2018-08-07 15:11 UTC, alxolr commented on src/app/shared/models/group.ts
> +  idSpecialty: string;
Specialty is ok spelled actually, we got on backend same issue

2018-08-07 15:31 UTC, vadim11041996 commented on src/app/modules/groups/components/add-group-modal/add-group-modal.component.html
> +<button type="button" class="btn btn-primary" (click)="openModal(template)">Add a new group</button>
yes, 
  if you have 1541 than you say "this is a set of numbers"
  if you have 1a41 than you say "this is string"
get it?

2018-08-07 15:33 UTC, vadim11041996 commented on src/app/modules/groups/components/edit-group-modal/edit-group-modal.component.html
> +<ng-template #template>
the button that is going to open the modal, is not a part of modal component, theese are different components, parrent component should have a button that'll open another component, in our case this "another component " is a modal.

2018-08-07 15:35 UTC, vadim11041996 commented on src/app/modules/groups/components/add-group-modal/add-group-modal.component.html
> +    <form [formGroup]="groupForm" (submit)="onSubmit()">
it doesn't matter , if all of us did it wrong, we should change it, this is why we are here

2018-08-07 16:09 UTC, vadim11041996 commented on src/app/modules/specialties/components/add-specialty-modal/add-specialty-modal.component.html
> +
<input type="text" id="name" class="form-control" placeholder="Name" formControlName="name"
               [ngClass]="{ 'is-invalid': isSubmitted && fields.name.errors }">

it's not loking good , having in one line 2 arguments, in another 3, use like everybody is using , and ng6-starter for this purpose was created, to have a standard model of how we should work in our project

2018-08-07 16:10 UTC, vadim11041996 commented on src/app/modules/specialties/containers/specialty-details-page/specialty-details-page.component.ts
> +    this.specialtiesService.deleteSpecialty(this.id).toPromise();
don't use toPromise, use subscribe,  i told you once about this

2018-08-08 06:16 UTC, mrRobot157 commented on src/app/modules/groups/components/add-group-modal/add-group-modal.component.html
> +<button type="button" class="btn btn-primary" (click)="openModal(template)">Add a new group</button>
nope , tf have this with button :D ?

2018-08-08 06:22 UTC, closed without merging